spring:
  application:
    name: referral-service
  datasource:
    url: jdbc:postgresql://localhost:5432/curanexus_referral
    username: curanexus
    password: curanexus
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    table: flyway_schema_history_referral
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
