package se.curanexus.referral.api.dto;

import se.curanexus.referral.domain.*;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

public record ReferralDto(
        UUID id,
        String referralReference,
        UUID patientId,
        String patientPersonnummer,
        String patientName,
        ReferralType referralType,
        ReferralStatus status,
        ReferralPriority priority,
        UUID senderUnitId,
        String senderUnitHsaId,
        String senderUnitName,
        UUID senderPractitionerId,
        String senderPractitionerHsaId,
        String senderPractitionerName,
        UUID receiverUnitId,
        String receiverUnitHsaId,
        String receiverUnitName,
        String requestedSpecialty,
        String reason,
        String diagnosisCode,
        String diagnosisText,
        String clinicalHistory,
        String currentStatus,
        String examinationsDone,
        String currentMedication,
        String allergies,
        String additionalInfo,
        UUID sourceEncounterId,
        UUID resultingEncounterId,
        LocalDate requestedDate,
        LocalDate validUntil,
        Instant createdAt,
        Instant sentAt,
        Instant receivedAt,
        Instant assessedAt,
        Instant completedAt,
        UUID assessorId,
        String assessorName,
        List<ReferralResponseDto> responses
) {
    public static ReferralDto from(Referral r) {
        return new ReferralDto(
                r.getId(),
                r.getReferralReference(),
                r.getPatientId(),
                r.getPatientPersonnummer(),
                r.getPatientName(),
                r.getReferralType(),
                r.getStatus(),
                r.getPriority(),
                r.getSenderUnitId(),
                r.getSenderUnitHsaId(),
                r.getSenderUnitName(),
                r.getSenderPractitionerId(),
                r.getSenderPractitionerHsaId(),
                r.getSenderPractitionerName(),
                r.getReceiverUnitId(),
                r.getReceiverUnitHsaId(),
                r.getReceiverUnitName(),
                r.getRequestedSpecialty(),
                r.getReason(),
                r.getDiagnosisCode(),
                r.getDiagnosisText(),
                r.getClinicalHistory(),
                r.getCurrentStatus(),
                r.getExaminationsDone(),
                r.getCurrentMedication(),
                r.getAllergies(),
                r.getAdditionalInfo(),
                r.getSourceEncounterId(),
                r.getResultingEncounterId(),
                r.getRequestedDate(),
                r.getValidUntil(),
                r.getCreatedAt(),
                r.getSentAt(),
                r.getReceivedAt(),
                r.getAssessedAt(),
                r.getCompletedAt(),
                r.getAssessorId(),
                r.getAssessorName(),
                r.getResponses().stream().map(ReferralResponseDto::from).toList()
        );
    }

    public static ReferralDto fromWithoutResponses(Referral r) {
        return new ReferralDto(
                r.getId(),
                r.getReferralReference(),
                r.getPatientId(),
                r.getPatientPersonnummer(),
                r.getPatientName(),
                r.getReferralType(),
                r.getStatus(),
                r.getPriority(),
                r.getSenderUnitId(),
                r.getSenderUnitHsaId(),
                r.getSenderUnitName(),
                r.getSenderPractitionerId(),
                r.getSenderPractitionerHsaId(),
                r.getSenderPractitionerName(),
                r.getReceiverUnitId(),
                r.getReceiverUnitHsaId(),
                r.getReceiverUnitName(),
                r.getRequestedSpecialty(),
                r.getReason(),
                r.getDiagnosisCode(),
                r.getDiagnosisText(),
                r.getClinicalHistory(),
                r.getCurrentStatus(),
                r.getExaminationsDone(),
                r.getCurrentMedication(),
                r.getAllergies(),
                r.getAdditionalInfo(),
                r.getSourceEncounterId(),
                r.getResultingEncounterId(),
                r.getRequestedDate(),
                r.getValidUntil(),
                r.getCreatedAt(),
                r.getSentAt(),
                r.getReceivedAt(),
                r.getAssessedAt(),
                r.getCompletedAt(),
                r.getAssessorId(),
                r.getAssessorName(),
                List.of()
        );
    }
}
