/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PatientsIndexImport } from './routes/patients/index'
import { Route as EncountersIndexImport } from './routes/encounters/index'
import { Route as PatientsPatientIdImport } from './routes/patients/$patientId'
import { Route as EncountersEncounterIdImport } from './routes/encounters/$encounterId'

// Create Virtual Routes

const TasksLazyImport = createFileRoute('/tasks')()
const BookingLazyImport = createFileRoute('/booking')()
const MedicationLazyImport = createFileRoute('/medication')()
const ReferralsLazyImport = createFileRoute('/referrals')()
const LabLazyImport = createFileRoute('/lab')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TasksLazyRoute = TasksLazyImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRoute,
} as any)

const BookingLazyRoute = BookingLazyImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRoute,
} as any)

const MedicationLazyRoute = MedicationLazyImport.update({
  id: '/medication',
  path: '/medication',
  getParentRoute: () => rootRoute,
} as any)

const ReferralsLazyRoute = ReferralsLazyImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRoute,
} as any)

const LabLazyRoute = LabLazyImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRoute,
} as any)

const PatientsIndexRoute = PatientsIndexImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRoute,
} as any)

const EncountersIndexRoute = EncountersIndexImport.update({
  id: '/encounters/',
  path: '/encounters/',
  getParentRoute: () => rootRoute,
} as any)

const PatientsPatientIdRoute = PatientsPatientIdImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRoute,
} as any)

const EncountersEncounterIdRoute = EncountersEncounterIdImport.update({
  id: '/encounters/$encounterId',
  path: '/encounters/$encounterId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksLazyImport
      parentRoute: typeof rootRoute
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingLazyImport
      parentRoute: typeof rootRoute
    }
    '/medication': {
      id: '/medication'
      path: '/medication'
      fullPath: '/medication'
      preLoaderRoute: typeof MedicationLazyImport
      parentRoute: typeof rootRoute
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsLazyImport
      parentRoute: typeof rootRoute
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabLazyImport
      parentRoute: typeof rootRoute
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsIndexImport
      parentRoute: typeof rootRoute
    }
    '/encounters/': {
      id: '/encounters/'
      path: '/encounters'
      fullPath: '/encounters'
      preLoaderRoute: typeof EncountersIndexImport
      parentRoute: typeof rootRoute
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdImport
      parentRoute: typeof rootRoute
    }
    '/encounters/$encounterId': {
      id: '/encounters/$encounterId'
      path: '/encounters/$encounterId'
      fullPath: '/encounters/$encounterId'
      preLoaderRoute: typeof EncountersEncounterIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tasks': typeof TasksLazyRoute
  '/booking': typeof BookingLazyRoute
  '/medication': typeof MedicationLazyRoute
  '/referrals': typeof ReferralsLazyRoute
  '/lab': typeof LabLazyRoute
  '/patients': typeof PatientsIndexRoute
  '/encounters': typeof EncountersIndexRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/encounters/$encounterId': typeof EncountersEncounterIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tasks': typeof TasksLazyRoute
  '/booking': typeof BookingLazyRoute
  '/medication': typeof MedicationLazyRoute
  '/referrals': typeof ReferralsLazyRoute
  '/lab': typeof LabLazyRoute
  '/patients': typeof PatientsIndexRoute
  '/encounters': typeof EncountersIndexRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/encounters/$encounterId': typeof EncountersEncounterIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/tasks': typeof TasksLazyRoute
  '/booking': typeof BookingLazyRoute
  '/medication': typeof MedicationLazyRoute
  '/referrals': typeof ReferralsLazyRoute
  '/lab': typeof LabLazyRoute
  '/patients/': typeof PatientsIndexRoute
  '/encounters/': typeof EncountersIndexRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/encounters/$encounterId': typeof EncountersEncounterIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tasks'
    | '/booking'
    | '/medication'
    | '/referrals'
    | '/lab'
    | '/patients'
    | '/encounters'
    | '/patients/$patientId'
    | '/encounters/$encounterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tasks'
    | '/booking'
    | '/medication'
    | '/referrals'
    | '/lab'
    | '/patients'
    | '/encounters'
    | '/patients/$patientId'
    | '/encounters/$encounterId'
  id:
    | '__root__'
    | '/'
    | '/tasks'
    | '/booking'
    | '/medication'
    | '/referrals'
    | '/lab'
    | '/patients/'
    | '/encounters/'
    | '/patients/$patientId'
    | '/encounters/$encounterId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TasksLazyRoute: typeof TasksLazyRoute
  BookingLazyRoute: typeof BookingLazyRoute
  MedicationLazyRoute: typeof MedicationLazyRoute
  ReferralsLazyRoute: typeof ReferralsLazyRoute
  LabLazyRoute: typeof LabLazyRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  EncountersIndexRoute: typeof EncountersIndexRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  EncountersEncounterIdRoute: typeof EncountersEncounterIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TasksLazyRoute: TasksLazyRoute,
  BookingLazyRoute: BookingLazyRoute,
  MedicationLazyRoute: MedicationLazyRoute,
  ReferralsLazyRoute: ReferralsLazyRoute,
  LabLazyRoute: LabLazyRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  EncountersIndexRoute: EncountersIndexRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  EncountersEncounterIdRoute: EncountersEncounterIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
