server:
  port: 8096

spring:
  application:
    name: audit-module
  datasource:
    url: jdbc:postgresql://localhost:5432/curanexus_audit
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /api/v1/audit/openapi
  swagger-ui:
    path: /api/v1/audit/swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
