package se.curanexus.audit.domain;

public enum SecurityEventType {
    LOGIN,
    LOGOUT,
    LOGIN_FAILED,
    PASSWORD_CHANGE,
    PASSWORD_RESET,
    PERMISSION_DENIED,
    ROLE_ASSIGNED,
    ROLE_REMOVED,
    EMERGENCY_ACCESS,
    CONSENT_OVERRIDE,
    MFA_ENABLED,
    MFA_DISABLED,
    SESSION_EXPIRED,
    SUSPICIOUS_ACTIVITY,
    ACCOUNT_LOCKED
}
